/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import access.OpcionesDAO;
import access.PreguntaDAO;
import controllers.InitialDataConfig;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import model.CategoriaModel;
import model.OpcionesModel;
import model.PreguntaModel;

/**
 *
 * @author lcast
 */
public class Configurar extends javax.swing.JPanel {

    JButton bBorrar = new JButton();
    /**
     * Creates new form Configurar
     */
    public Configurar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        AgregarP = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        OptionsGroup = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        InitialDataConfig initialDataConfig = new InitialDataConfig(1);
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        AgregarP.setBackground(new java.awt.Color(153, 153, 255));
        AgregarP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AgregarP.getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel3.setText("Pregunta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        AgregarP.getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("Ingrese el enunciado de la pregunta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 0, 0);
        AgregarP.getContentPane().add(jLabel4, gridBagConstraints);

        jTextField1.setToolTipText("Por favor escriba su pregunta.");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.ipadx = 369;
        gridBagConstraints.ipady = 39;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 12);
        AgregarP.getContentPane().add(jTextField1, gridBagConstraints);

        jLabel7.setText("Ingrese las posibles Opciones y seleccione la correcta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 12, 0, 0);
        AgregarP.getContentPane().add(jLabel7, gridBagConstraints);

        OptionsGroup.add(jRadioButton1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 12, 0, 0);
        AgregarP.getContentPane().add(jRadioButton1, gridBagConstraints);

        OptionsGroup.add(jRadioButton2);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 12, 0, 0);
        AgregarP.getContentPane().add(jRadioButton2, gridBagConstraints);

        OptionsGroup.add(jRadioButton3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 0, 0);
        AgregarP.getContentPane().add(jRadioButton3, gridBagConstraints);

        OptionsGroup.add(jRadioButton4);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 12, 0, 0);
        AgregarP.getContentPane().add(jRadioButton4, gridBagConstraints);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 340;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 8, 0, 12);
        AgregarP.getContentPane().add(jTextField2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 340;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 8, 0, 12);
        AgregarP.getContentPane().add(jTextField3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 340;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 8, 0, 12);
        AgregarP.getContentPane().add(jTextField4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 340;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(7, 8, 0, 12);
        AgregarP.getContentPane().add(jTextField6, gridBagConstraints);

        jButton3.setBackground(java.awt.SystemColor.inactiveCaption);
        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 22, 19, 12);
        AgregarP.getContentPane().add(jButton3, gridBagConstraints);

        setBackground(new java.awt.Color(153, 153, 255));
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(1020, 720));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel2.setText("Categoría:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(39, 70, 0, 0);
        add(jLabel2, gridBagConstraints);

        jComboBox1.setBackground(java.awt.SystemColor.inactiveCaption);
        jComboBox1.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new DefaultComboBoxModel(initialDataConfig.getCategorias().toArray(new CategoriaModel[initialDataConfig.getCategorias().size()])));
        jComboBox1.setSelectedIndex(0);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 115;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 18, 0, 0);
        add(jComboBox1, gridBagConstraints);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(java.awt.SystemColor.inactiveCaption);
        jTable1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        ArrayList<PreguntaModel> preguntas = initialDataConfig.getPreguntas();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        String[] headers = {"Id", "Enunciado", "Eliminar"};
        this.jTable1.removeAll();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(headers);
        this.jTable1.setModel(tableModel);
        for(int i=0; i<preguntas.size(); i++){
            tableModel.addRow(preguntas.get(i).toArray());
        }
        jTable1.getColumn("Eliminar").setCellRenderer(new ButtonRenderer());
        jTable1.getColumn("Eliminar").setCellEditor(new ButtonEditor(new JCheckBox()));
        jTable1.setRowHeight(40);

        bBorrar.addActionListener(
            new ActionListener() {
                public void actionPerformed(ActionEvent event) {
                    if (JOptionPane.showConfirmDialog(null,"Desea eliminar esta pregunta?","Mensaje del Sistema",JOptionPane.YES_NO_OPTION)==0) {
                        int preID = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
                        OpcionesDAO opcion = new OpcionesDAO();
                        ArrayList<OpcionesModel> opcionespre = opcion.obtenerOpcionesxPre(preID);
                        if (opcionespre.size() > 0) {
                            for (int i = 0; i < opcionespre.size(); ++i) {
                                int opId = opcionespre.get(i).getOpID();
                                opcion.eliminarOpcion(opId);
                            }
                        }
                        PreguntaDAO pregunta = new PreguntaDAO();
                        pregunta.eliminarPregunta(preID);
                    };
                    refreshTable();
                }
            }
        );
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 939;
        gridBagConstraints.ipady = 513;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(38, 29, 13, 29);
        add(jScrollPane1, gridBagConstraints);

        jButton1.setBackground(java.awt.SystemColor.inactiveCaption);
        jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jButton1.setText("Agregar Pregunta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 313, 0, 0);
        add(jButton1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel1.setText("Seleccione el nivel de dificultad y agregue 5 o más preguntas por nivel");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(42, 29, 0, 0);
        add(jLabel1, gridBagConstraints);

        jButton2.setBackground(java.awt.SystemColor.inactiveCaption);
        jButton2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        jButton2.setText("Atrás");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.BELOW_BASELINE_TRAILING;
        add(jButton2, gridBagConstraints);

        getAccessibleContext().setAccessibleParent(jButton1);
    }// </editor-fold>//GEN-END:initComponents

    class ButtonRenderer extends JButton implements TableCellRenderer {
        public ButtonRenderer() {
            setOpaque(true);
        }
        public Component getTableCellRendererComponent(JTable table, Object value,boolean isSelected, boolean hasFocus, int row, int column) {
            setText((value == null) ? "Borrar" : value.toString());
            return this;
        }
    }

    class ButtonEditor extends DefaultCellEditor {
        private String label;

        public ButtonEditor(JCheckBox checkBox) {
            super(checkBox);
        }

        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            label = (value == null) ? "Borrar" : value.toString();
            bBorrar.setText(label);
            return bBorrar;
        }

        public Object getCellEditorValue() {
            return new String(label);
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
        this.setVisible(false);
        Container container = this.getParent();
        container.getComponent(0).setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AgregarP.setSize(500,500);
        AgregarP.setLocationRelativeTo(null);
        AgregarP.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Boolean lOk = true;
        if (jTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "El enunciado de la pregunta, NO puede dejarse en blanco", "Error!", JOptionPane.ERROR_MESSAGE);
            lOk = false;
        }
        if (jTextField2.getText().isEmpty() && lOk){
            JOptionPane.showMessageDialog(this, "La primera opción de la pregunta, NO puede dejarse en blanco", "Error!", JOptionPane.ERROR_MESSAGE);
            lOk = false;
        }
        if (jTextField3.getText().isEmpty() && lOk){
            JOptionPane.showMessageDialog(this, "La segunda opción de la pregunta, NO puede dejarse en blanco", "Error!", JOptionPane.ERROR_MESSAGE);
            lOk = false;
        }
        if (jTextField4.getText().isEmpty() && lOk){
            JOptionPane.showMessageDialog(this, "La tercera opción de la pregunta, NO puede dejarse en blanco", "Error!", JOptionPane.ERROR_MESSAGE);
            lOk = false;
        }
        if (jTextField6.getText().isEmpty() && lOk){
            JOptionPane.showMessageDialog(this, "La cuarta opción de la pregunta, NO puede dejarse en blanco", "Error!", JOptionPane.ERROR_MESSAGE);
            lOk = false;
        }
        if (!((jRadioButton1.isSelected()) || (jRadioButton2.isSelected()) || (jRadioButton3.isSelected()) || (jRadioButton4.isSelected()))) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar cual es la opción verdadera", "Error!", JOptionPane.ERROR_MESSAGE);
            lOk = false;
        }
        if (lOk) {
            CategoriaModel categoria = (CategoriaModel) jComboBox1.getSelectedItem();
            int catId = categoria.getCatID();
            PreguntaModel pregunta = new PreguntaModel(0, catId, jTextField1.getText());
            PreguntaDAO preguntaDAO = new PreguntaDAO();
            pregunta.setPreID(preguntaDAO.agregarPregunta(pregunta));
            // se insertan las cuatro opciones
            OpcionesDAO opcionesDAO = new OpcionesDAO();
            OpcionesModel opciones1 = new OpcionesModel(0, pregunta.getPreID(), jTextField2.getText(), jRadioButton1.isSelected());
            opcionesDAO.agregarOpcion(opciones1);
            OpcionesModel opciones2 = new OpcionesModel(0, pregunta.getPreID(), jTextField3.getText(), jRadioButton2.isSelected());
            opcionesDAO.agregarOpcion(opciones2);
            OpcionesModel opciones3 = new OpcionesModel(0, pregunta.getPreID(), jTextField4.getText(), jRadioButton3.isSelected());
            opcionesDAO.agregarOpcion(opciones3);
            OpcionesModel opciones4 = new OpcionesModel(0, pregunta.getPreID(), jTextField6.getText(), jRadioButton4.isSelected());
            opcionesDAO.agregarOpcion(opciones4);
            refreshTable();
            AgregarP.dispose();

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void refreshTable() {
        CategoriaModel categoria = (CategoriaModel) jComboBox1.getSelectedItem();
        int catId = categoria.getCatID();
        InitialDataConfig initialData = new InitialDataConfig(catId);
        ArrayList<PreguntaModel> preguntas = initialData.getPreguntas();
        String[] headers = {"Id", "Enunciado", "Eliminar"};
        this.jTable1.removeAll();
        DefaultTableModel tableModel = new DefaultTableModel();
        tableModel.setColumnIdentifiers(headers);
        this.jTable1.setModel(tableModel);
        for(int i=0; i<preguntas.size(); i++){
            tableModel.addRow(preguntas.get(i).toArray());
        }
        jTable1.getColumn("Eliminar").setCellRenderer(new ButtonRenderer());
        jTable1.getColumn("Eliminar").setCellEditor(new ButtonEditor(new JCheckBox()));
        jTable1.setRowHeight(40);

        bBorrar.addActionListener(
            new ActionListener() {
                public void actionPerformed(ActionEvent event) {
                    if (JOptionPane.showConfirmDialog(null,"Desea eliminar esta pregunta?","Mensaje del Sistema",JOptionPane.YES_NO_OPTION)==0) {
                        int preID = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
                        OpcionesDAO opcion = new OpcionesDAO();
                        ArrayList<OpcionesModel> opcionespre = opcion.obtenerOpcionesxPre(preID);
                        if (opcionespre.size() > 0) {
                            for (int i = 0; i < opcionespre.size(); ++i) {
                                int opId = opcionespre.get(i).getOpID();
                                opcion.eliminarOpcion(opId);
                            }
                        }
                        PreguntaDAO pregunta = new PreguntaDAO();
                        pregunta.eliminarPregunta(preID);
                    };
                }
            }
        );
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);

    }
    
    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_jComboBox1ItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame AgregarP;
    private javax.swing.ButtonGroup OptionsGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
    // Se inicializan los datos
}
